name: Deploy ArgoCD
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Add ArgoCD Helm repo
      run: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update

    - name: Deploy ArgoCD with Helm
      run: |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          -f helm/argocd/values.yaml

    - name: Verify ArgoCD deployment
      run: kubectl get pods -n argocd
